// Sticker fuer den TanzRaum-Messenger. Die Bilder liegen unter public/sticker/<satz>/<id>.webp,
// die IDs sind zusaetzlich in der Tabelle public.sticker hinterlegt (Nachrichten referenzieren sie).

export type StickerSatz = "taenzerin" | "gardist";

export type Sticker = { id: string; satz: StickerSatz; name: string };

export const STICKER_SAETZE: { satz: StickerSatz; titel: string }[] = [
  { satz: "taenzerin", titel: "Tänzerin" },
  { satz: "gardist", titel: "Gardist" },
];

export const STICKER: Sticker[] = [
  { id: "t01", satz: "taenzerin", name: "Daumen hoch" },
  { id: "t02", satz: "taenzerin", name: "Herzhände" },
  { id: "t03", satz: "taenzerin", name: "Verliebt" },
  { id: "t04", satz: "taenzerin", name: "Kusshand" },
  { id: "t05", satz: "taenzerin", name: "Schüchtern" },
  { id: "t06", satz: "taenzerin", name: "Kick" },
  { id: "t07", satz: "taenzerin", name: "Juhu" },
  { id: "t08", satz: "taenzerin", name: "Glitzer" },
  { id: "t09", satz: "taenzerin", name: "Vorfreude" },
  { id: "t10", satz: "taenzerin", name: "Bein hoch" },
  { id: "t11", satz: "taenzerin", name: "Standwaage" },
  { id: "t12", satz: "taenzerin", name: "Spagat" },
  { id: "t13", satz: "taenzerin", name: "Sprung" },
  { id: "t14", satz: "taenzerin", name: "Brücke" },
  { id: "t15", satz: "taenzerin", name: "Stretching" },
  { id: "t16", satz: "taenzerin", name: "Seitspagat" },
  { id: "t17", satz: "taenzerin", name: "Beinheben" },
  { id: "t18", satz: "taenzerin", name: "Arabeske" },
  { id: "t19", satz: "taenzerin", name: "Gruppenumarmung" },
  { id: "t20", satz: "taenzerin", name: "High Five" },
  { id: "t21", satz: "taenzerin", name: "Freundinnen" },
  { id: "t22", satz: "taenzerin", name: "Pokal" },
  { id: "t23", satz: "taenzerin", name: "Herz" },
  { id: "t24", satz: "taenzerin", name: "Pompons" },
  { id: "t25", satz: "taenzerin", name: "Megafon" },
  { id: "t26", satz: "taenzerin", name: "Stern" },
  { id: "t27", satz: "taenzerin", name: "Cool" },
  { id: "t28", satz: "taenzerin", name: "Lachtränen" },
  { id: "t29", satz: "taenzerin", name: "Herzaugen" },
  { id: "t30", satz: "taenzerin", name: "Staunen" },
  { id: "t31", satz: "taenzerin", name: "Pssst" },
  { id: "t32", satz: "taenzerin", name: "Schelmisch" },
  { id: "t33", satz: "taenzerin", name: "Stark" },
  { id: "t34", satz: "taenzerin", name: "Wütend" },
  { id: "t35", satz: "taenzerin", name: "Traurig" },
  { id: "t36", satz: "taenzerin", name: "Verträumt" },
  { id: "t37", satz: "taenzerin", name: "Laptop" },
  { id: "t38", satz: "taenzerin", name: "Handy" },
  { id: "t39", satz: "taenzerin", name: "Termin" },
  { id: "t40", satz: "taenzerin", name: "Pünktlich" },
  { id: "t41", satz: "taenzerin", name: "Alles klar" },
  { id: "t42", satz: "taenzerin", name: "Winken" },
  { id: "t43", satz: "taenzerin", name: "Müde" },
  { id: "t44", satz: "taenzerin", name: "Idee" },
  { id: "t45", satz: "taenzerin", name: "Fragen" },
  { id: "t46", satz: "taenzerin", name: "Musik" },
  { id: "t47", satz: "taenzerin", name: "Herzen" },
  { id: "t48", satz: "taenzerin", name: "Trinken" },
  { id: "t49", satz: "taenzerin", name: "Herz umarmen" },
  { id: "t50", satz: "taenzerin", name: "Jubeln" },
  { id: "t51", satz: "taenzerin", name: "Peace" },
  { id: "t52", satz: "taenzerin", name: "Star" },
  { id: "t53", satz: "taenzerin", name: "Team" },
  { id: "t54", satz: "taenzerin", name: "Hurra" },
  { id: "t55", satz: "taenzerin", name: "Da oben" },
  { id: "t56", satz: "taenzerin", name: "Kichern" },
  { id: "t57", satz: "taenzerin", name: "Party" },
  { id: "t58", satz: "taenzerin", name: "Hallo?" },
  { id: "t59", satz: "taenzerin", name: "Oh!" },
  { id: "t60", satz: "taenzerin", name: "Hmm?" },
  { id: "t61", satz: "taenzerin", name: "Hihi" },
  { id: "t62", satz: "taenzerin", name: "Tanzen" },
  { id: "t63", satz: "taenzerin", name: "Dehnen" },
  { id: "t64", satz: "taenzerin", name: "Notizen" },
  { id: "t65", satz: "taenzerin", name: "Checkliste" },
  { id: "t66", satz: "taenzerin", name: "Tanzen mit Musik" },
  { id: "t67", satz: "taenzerin", name: "Drehung" },
  { id: "t68", satz: "taenzerin", name: "Du!" },
  { id: "t69", satz: "taenzerin", name: "Auftritt" },
  { id: "t70", satz: "taenzerin", name: "TEAM" },
  { id: "t71", satz: "taenzerin", name: "Ich seh dich" },
  { id: "t72", satz: "taenzerin", name: "Banane" },
  { id: "t73", satz: "taenzerin", name: "Lässig" },
  { id: "t74", satz: "taenzerin", name: "Entspannt" },
  { id: "t75", satz: "taenzerin", name: "Gestresst" },
  { id: "t76", satz: "taenzerin", name: "Geburtstag" },
  { id: "t77", satz: "taenzerin", name: "Feiern" },
  { id: "t78", satz: "taenzerin", name: "Blumen" },
  { id: "t79", satz: "taenzerin", name: "Weinen" },
  { id: "t80", satz: "taenzerin", name: "Superstar" },
  { id: "t81", satz: "taenzerin", name: "Tanzpartnerin" },
  { id: "t82", satz: "taenzerin", name: "Chillen" },
  { id: "t83", satz: "taenzerin", name: "Genervt" },
  { id: "g01", satz: "gardist", name: "Daumen hoch" },
  { id: "g02", satz: "gardist", name: "Lächeln" },
  { id: "g03", satz: "gardist", name: "Zwinkern" },
  { id: "g04", satz: "gardist", name: "Herzhände" },
  { id: "g05", satz: "gardist", name: "Lachen" },
  { id: "g06", satz: "gardist", name: "Selbstbewusst" },
  { id: "g07", satz: "gardist", name: "Freude" },
  { id: "g08", satz: "gardist", name: "Cool" },
  { id: "g09", satz: "gardist", name: "Pssst" },
  { id: "g10", satz: "gardist", name: "Bein hoch" },
  { id: "g11", satz: "gardist", name: "Tanzpose" },
  { id: "g12", satz: "gardist", name: "Tanzpose 2" },
  { id: "g13", satz: "gardist", name: "Sprung" },
  { id: "g14", satz: "gardist", name: "Hochsprung" },
  { id: "g15", satz: "gardist", name: "Pompons" },
  { id: "g16", satz: "gardist", name: "Ausfallschritt" },
  { id: "g17", satz: "gardist", name: "Pokal" },
  { id: "g18", satz: "gardist", name: "Pompon-Kick" },
  { id: "g19", satz: "gardist", name: "Musik" },
  { id: "g20", satz: "gardist", name: "Laptop" },
  { id: "g21", satz: "gardist", name: "Super" },
  { id: "g22", satz: "gardist", name: "Megafon" },
  { id: "g23", satz: "gardist", name: "Hurra" },
  { id: "g24", satz: "gardist", name: "Herz" },
  { id: "g25", satz: "gardist", name: "Grinsen" },
  { id: "g26", satz: "gardist", name: "Trommel" },
  { id: "g27", satz: "gardist", name: "Idee" },
  { id: "g28", satz: "gardist", name: "Freunde" },
  { id: "g29", satz: "gardist", name: "Pompon" },
  { id: "g30", satz: "gardist", name: "Trinken" },
  { id: "g31", satz: "gardist", name: "Müde" },
  { id: "g32", satz: "gardist", name: "Los geht's" },
  { id: "g33", satz: "gardist", name: "Stolz" },
  { id: "g34", satz: "gardist", name: "Stern" },
  { id: "g35", satz: "gardist", name: "Medaille" },
  { id: "g36", satz: "gardist", name: "Frage" },
  { id: "g37", satz: "gardist", name: "Power" },
  { id: "g38", satz: "gardist", name: "Pfeife" },
  { id: "g39", satz: "gardist", name: "Tanzen" },
  { id: "g40", satz: "gardist", name: "Arme auf" },
  { id: "g41", satz: "gardist", name: "Singen" },
  { id: "g42", satz: "gardist", name: "Ansage" },
  { id: "g43", satz: "gardist", name: "Jubel" },
  { id: "g44", satz: "gardist", name: "Spagat" },
  { id: "g45", satz: "gardist", name: "Seitspagat" },
  { id: "g46", satz: "gardist", name: "Gruppe" },
  { id: "g47", satz: "gardist", name: "Musik hören" },
  { id: "g48", satz: "gardist", name: "Musizieren" },
  { id: "g49", satz: "gardist", name: "Sieger" },
  { id: "g50", satz: "gardist", name: "Akrobatik" },
];

const NACH_ID = new Map(STICKER.map((s) => [s.id, s]));

export function stickerInfo(id: string | null | undefined): Sticker | null {
  return id ? (NACH_ID.get(id) ?? null) : null;
}

export function stickerUrl(id: string): string {
  const s = NACH_ID.get(id);
  return `/sticker/${s?.satz ?? "taenzerin"}/${id}.webp`;
}
