-- Ehrungen & Orden – initiale Befuellung aus dem Ehrungs-Kompendium (Arbeitsgrundlage)
--
-- Uebernommen wird ausschliesslich, was im Kompendium steht. Nichts wurde ergaenzt oder erfunden:
-- * 38 Organisationen: BDK (Dachverband), 35 Regionalverbaende, 2 unabhaengige Traditionsverbaende
-- * BDK-Verdienstorden Silber (15 J.) und Gold (25 J.) mit Regel "aktive Taetigkeit"; Gold mit Brillanten nur manuell
--   (Einzelfallpruefung laut Kompendium)
-- * Spitzenorden der Regionalverbaende nur als Name, ohne Kriterien (im Kompendium keiner Auszeichnung zugeordnet)
-- Alle Eintraege: Pruefstatus "nicht_geprueft". Auffaelligkeiten stehen in pruef_bemerkung.
-- Idempotent: bereits vorhandene Eintraege (gleicher Name) werden nicht doppelt angelegt.

insert into public.ehrungs_organisationen (name, kuerzel, art, beschreibung, quelle, pruefstatus, verband_id) values
  ('Bund Deutscher Karneval e.V.', 'BDK', 'dachverband', 'Dachverband; stellt die übergeordneten Richtlinien. Seine Orden überlagern die regionalen Systeme.', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'nicht_geprueft', (select v.id from public.verbaende v where v.kuerzel = 'BDK'))
on conflict (name) do nothing;

insert into public.ehrungs_organisationen (name, kuerzel, art, uebergeordnet_id, beschreibung, quelle, pruef_bemerkung, pruefstatus)
select x.name, x.kuerzel, 'regionalverband', (select id from public.ehrungs_organisationen where name = 'Bund Deutscher Karneval e.V.'), x.beschreibung, x.quelle, x.bemerkung, 'nicht_geprueft'
from (values
  ('Vereinigung Badisch-Pfälzischer Karnevalvereine', null, 'Verleihungsregel / System laut Kompendium: Strenges 11-Punkte-System (Vorstand 1 Pkt/Jahr; Aktive 0,5 Pkt/Jahr)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Das Punktesystem ist im Kompendium keiner bestimmten Auszeichnung zugeordnet – deshalb keine automatische Regel hinterlegt.'),
  ('Landesverband Württembergischer Karnevalvereine', 'LWK', 'Verleihungsregel / System laut Kompendium: Zeitspezifische Staffelung (11, 22 Jahre); kein reines Punktezählen', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Staffelung ist keiner bestimmten Auszeichnung zugeordnet.'),
  ('Interessengemeinschaft Mittelrheinischer Karneval', 'IGMK', 'Verleihungsregel / System laut Kompendium: Kombination aus Funktionsjahren (11-35 Jahre Vorstand)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund Ruhr-Karneval e.V.', 'BRK', 'Verleihungsregel / System laut Kompendium: Fokus auf Jugendarbeit & langjährige Präsidentschaft', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Regional-Verband Rhein-Sieg-Eifel e.V.', 'RSE', 'Verleihungsregel / System laut Kompendium: Strukturierte Anwartschaft nach rheinischem Komment (11/22/33)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('FestAusschuss Aachener Karneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Traditionsbasiert, Fokus auf Brauchtumserhalt im Aachener Raum', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Möglicherweise doppelt: Das Kompendium führt zusätzlich den „Ausschuss Aachener Karneval e.V.“.'),
  ('Karnevalsverband Rhein-Erft e.V.', null, 'Verleihungsregel / System laut Kompendium: Jahresfristen (11, 22, 33 Jahre), lückenloser Nachweis nötig', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund Westfälischer Karneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Quotenregelung pro Verein, zeitliche Mindestgrenzen (15/25 J.)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Karnevalverband Berlin-Brandenburg e.V.', null, 'Verleihungsregel / System laut Kompendium: Hauptstadtregelung, Berücksichtigung von Landesmeisterschaften', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Mitteldeutscher Karneval-Verband e.V.', null, 'Verleihungsregel / System laut Kompendium: Zusammenfassung Sachsen, Sachsen-Anhalt, Thüringen; Zeitstufen', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Widerspruch im Kompendium: Sachsen, Sachsen-Anhalt und Thüringen sind zusätzlich als eigene Verbände aufgeführt.'),
  ('Karneval-Verband Niedersachsen e.V.', null, 'Verleihungsregel / System laut Kompendium: Zeitmodell (11, 22, 33 Jahre aktiv)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Verband Saarländischer Karnevalsvereine e.V.', null, 'Verleihungsregel / System laut Kompendium: Ähnlich Pfalz, enge Anbindung an französische Grenzvereine', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Karnevalverband Kurhessen e.V.', null, 'Verleihungsregel / System laut Kompendium: Regionale Ausprägungen im nordhessischen Raum', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund Deutscher Karneval - LV Thüringen', null, 'Verleihungsregel / System laut Kompendium: Eigenständiger Landesverband unter BDK; 10/20/30 Jahre', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Siehe Mitteldeutscher Karneval-Verband (Überschneidung laut Kompendium).'),
  ('Karnevalsverband Sachsen-Anhalt e.V.', null, 'Verleihungsregel / System laut Kompendium: Aufbau- und Entwicklungsorden nach der Wende integriert', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Siehe Mitteldeutscher Karneval-Verband (Überschneidung laut Kompendium).'),
  ('Verband Sächsischer Carneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Fokus auf Tanzsport-Erfolge und Vereinsgründungen', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Siehe Mitteldeutscher Karneval-Verband (Überschneidung laut Kompendium).'),
  ('Karneval-Verband Mecklenburg-Vorpommern', null, 'Verleihungsregel / System laut Kompendium: Junge Strukturen, Ehrung für Reaktivierung des Brauchtums', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Landesverband Bayerisch-Schwäbischer Fastnachtsvereine', null, 'Verleihungsregel / System laut Kompendium: Faschingstradition, mathematische Stunden-/Jahreskontrollen', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Fastnacht-Verband Franken e.V.', null, 'Verleihungsregel / System laut Kompendium: Sehr einflussreich, eigene strenge Kriterien (Sitzung Franken)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund Oberpfälzer Karnevalvereine', null, 'Verleihungsregel / System laut Kompendium: Regionale bayerische Struktur, 11- und 22-Jahre-Regel', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Verband Ostbayerischer Faschingsgesellschaften', null, 'Verleihungsregel / System laut Kompendium: Niederbayern/Oberpfalz; Fokus auf Prinzenpaare', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Landesverband Oberbayerischer Faschingsvereine', null, 'Verleihungsregel / System laut Kompendium: Faschingshochburg München/Umland; Eventfokus', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund der Karnevalisten an Rhein, Mosel und Lahn', null, 'Verleihungsregel / System laut Kompendium: Klassische rheinische Staffelung (Eifel/Mosel-Raum)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Ausschuss Aachener Karneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Lokale Besonderheit im BDK (Stadtebene)', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'Möglicherweise doppelt: Das Kompendium führt zusätzlich den „FestAusschuss Aachener Karneval e.V.“.'),
  ('Festausschuss Bonner Karneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Stadtebene Bonn, strenge Vergabe nur für Traditionskorps', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Gemeinschaft Dürener Karneval e.V.', null, 'Verleihungsregel / System laut Kompendium: Lokaler Kreisverband im BDK', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Karnevalsverband links und rechts des Rheins', null, 'Verleihungsregel / System laut Kompendium: Grenzübergreifend NRW/Rheinland-Pfalz', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Kreiskarnevalsverband Heinsberg e.V.', null, 'Verleihungsregel / System laut Kompendium: Westlichster Verband Deutschlands', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Münsterländer Karnevalsverband e.V.', null, 'Verleihungsregel / System laut Kompendium: Spezifisch für das Münsterland; hohe Hürden für Fremde', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Regionalverband Karnevalistischer Korporationen', 'RKK', 'Verleihungsregel / System laut Kompendium: Großer Verband, teils konkurrierend aber kooperierend', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'In TanzRaum ist RKK als „Rheinische Karnevals-Korporationen“ hinterlegt – Bezeichnung prüfen.'),
  ('Südwestdeutscher Karnevalsverband e.V.', null, 'Verleihungsregel / System laut Kompendium: Historischer Verband im südbadischen Raum', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Verband Hessischer Fastnachtsvereine e.V.', null, 'Verleihungsregel / System laut Kompendium: Zuständig für Süd- und Mittelhessen', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Verband Schleswig-Holsteinischer Karnevalisten', null, 'Verleihungsregel / System laut Kompendium: Nördlichster Verband, Fokus auf Minderheiten & Integration', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Bund Karnevalistischer Organisationen Ulm', null, 'Verleihungsregel / System laut Kompendium: Lokaler Verband an der Donau; Donauraum-Sonderstufe', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null),
  ('Vereinigung Trierer Karnevalisten e.V.', null, 'Verleihungsregel / System laut Kompendium: Älteste Kulturstadt Deutschlands, Fokus auf historische Bezüge', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', null)
) x(name, kuerzel, beschreibung, quelle, bemerkung)
on conflict (name) do nothing;

insert into public.ehrungs_organisationen (name, kuerzel, art, beschreibung, quelle, pruefstatus) values
  ('Vereinigung Schwäbisch-Alemannischer Narrenzünfte e.V.', 'VSAN', 'traditionsverband', 'Laut Kompendium: Keine Vergabe nach mathematischen Punkten oder Kampagnen-Dienstzeit. Die Ehrung erfolgt ausschließlich über die jahrzehntelange Treue zur eigenen Narrenzunft, die Weitergabe des Schnitzhandwerks für Holzmasken oder das Tragen des Häses (Traditionskostüm). Höchste Auszeichnungen sind meist rein ideeller Natur oder handgeschnitzte Unikate.', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'nicht_geprueft'),
  ('Kölner Festkomitee von 1823 e.V.', null, 'traditionsverband', 'Laut Kompendium: Obwohl eng mit dem BDK verzahnt, besitzt das Festkomitee Kölner Karneval ein autonomes Vergabesystem für den Verdienstorden des Kölner Karnevals. Hier zählt vor allem der strukturelle Beitrag zum Erhalt des Kölner Ur-Brauchtums und die Arbeit in den Kölner Traditionskorps.', 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'nicht_geprueft')
on conflict (name) do nothing;

insert into public.ehrungsarten (typ, organisation_id, serie, name, stufe, stufe_nr, kategorie, voraussetzungen, pruef_bemerkung, quelle, pruefstatus, automatische_vorschlaege, bestellung_erforderlich)
select 'verband', o.id, x.serie, x.name, x.stufe, x.stufe_nr, x.kategorie, x.voraussetzungen, x.bemerkung, 'Ehrungs-Kompendium „Gesamtkompendium: Auszeichnungen & Orden im deutschen Karneval“ – Arbeitsgrundlage, nicht auf Aktualität/Fehlerfreiheit geprüft (übernommen am 26.09.2026)', 'nicht_geprueft', true, true
from (values
  ('Bund Deutscher Karneval e.V.', 'BDK-Verdienstorden', 'Verdienstorden in Silber', 'Silber', 1, 'Dienstauszeichnung', '15 Jahre aktive Arbeit. Besonderheit: Ununterbrochene Treue zum Brauchtum.', 'Ob die 15 Jahre ununterbrochen sein müssen, geht aus dem Kompendium nicht eindeutig hervor – Regel ohne „ununterbrochen“ hinterlegt.'),
  ('Bund Deutscher Karneval e.V.', 'BDK-Verdienstorden', 'Verdienstorden in Gold', 'Gold', 2, 'Dienstauszeichnung', '25 Jahre aktive Arbeit. Besonderheit: Höchste reguläre Dienstauszeichnung.', null),
  ('Bund Deutscher Karneval e.V.', 'BDK-Verdienstorden', 'Verdienstorden in Gold mit Brillanten', 'Gold mit Brillanten', 3, 'Dienstauszeichnung', '40 Jahre ununterbrochen. Besonderheit: Sehr seltene Verleihung, erfordert Einzelfallprüfung.', 'Wegen Einzelfallprüfung nur manuelle Vergabe (keine automatische Regel).'),
  ('Vereinigung Badisch-Pfälzischer Karnevalvereine', null, 'Goldener Löwe', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Strenges 11-Punkte-System (Vorstand 1 Pkt/Jahr; Aktive 0,5 Pkt/Jahr)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Vereinigung Badisch-Pfälzischer Karnevalvereine', null, 'Goldener Löwe mit Brillant', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Strenges 11-Punkte-System (Vorstand 1 Pkt/Jahr; Aktive 0,5 Pkt/Jahr)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Landesverband Württembergischer Karnevalvereine', null, 'Hirsch am Goldenen Vlies', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Zeitspezifische Staffelung (11, 22 Jahre); kein reines Punktezählen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Landesverband Württembergischer Karnevalvereine', null, 'Großkreuze', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Zeitspezifische Staffelung (11, 22 Jahre); kein reines Punktezählen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Interessengemeinschaft Mittelrheinischer Karneval', null, 'Verdienstorden Gold mit Brillanten', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Kombination aus Funktionsjahren (11-35 Jahre Vorstand)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund Ruhr-Karneval e.V.', null, 'Ruhr-Verdienstorden in Sonderstufe', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Fokus auf Jugendarbeit & langjährige Präsidentschaft', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Regional-Verband Rhein-Sieg-Eifel e.V.', null, 'RSE-Verdienstorden in Gold', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Strukturierte Anwartschaft nach rheinischem Komment (11/22/33)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('FestAusschuss Aachener Karneval e.V.', null, 'Aachener Prunkorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Traditionsbasiert, Fokus auf Brauchtumserhalt im Aachener Raum', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('FestAusschuss Aachener Karneval e.V.', null, 'Verdienstkreuze', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Traditionsbasiert, Fokus auf Brauchtumserhalt im Aachener Raum', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karnevalsverband Rhein-Erft e.V.', null, 'Verdienstmedaille in Gold', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Jahresfristen (11, 22, 33 Jahre), lückenloser Nachweis nötig', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund Westfälischer Karneval e.V.', null, 'Westfalen-Verdienstorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Quotenregelung pro Verein, zeitliche Mindestgrenzen (15/25 J.)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karnevalverband Berlin-Brandenburg e.V.', null, 'Verdienstorden in Gold mit Brillanten', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Hauptstadtregelung, Berücksichtigung von Landesmeisterschaften', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Mitteldeutscher Karneval-Verband e.V.', null, 'Mitteldeutscher Verdienstorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Zusammenfassung Sachsen, Sachsen-Anhalt, Thüringen; Zeitstufen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karneval-Verband Niedersachsen e.V.', null, 'Niedersachsen-Sonderorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Zeitmodell (11, 22, 33 Jahre aktiv)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Verband Saarländischer Karnevalsvereine e.V.', null, 'Saarländischer Verdienstorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Ähnlich Pfalz, enge Anbindung an französische Grenzvereine', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karnevalverband Kurhessen e.V.', null, 'Kurhessen-Orden am Bande', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Regionale Ausprägungen im nordhessischen Raum', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund Deutscher Karneval - LV Thüringen', null, 'Thüringer Löwenorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Eigenständiger Landesverband unter BDK; 10/20/30 Jahre', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karnevalsverband Sachsen-Anhalt e.V.', null, 'Sachsen-Anhalt Verdienstkreuz', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Aufbau- und Entwicklungsorden nach der Wende integriert', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Verband Sächsischer Carneval e.V.', null, 'Sächsischer Verdienstorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Fokus auf Tanzsport-Erfolge und Vereinsgründungen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karneval-Verband Mecklenburg-Vorpommern', null, 'MV-Ehrenring', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Junge Strukturen, Ehrung für Reaktivierung des Brauchtums', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Landesverband Bayerisch-Schwäbischer Fastnachtsvereine', null, 'St. Georgs-Orden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Faschingstradition, mathematische Stunden-/Jahreskontrollen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Fastnacht-Verband Franken e.V.', null, 'Till von Franken', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Sehr einflussreich, eigene strenge Kriterien (Sitzung Franken)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund Oberpfälzer Karnevalvereine', null, 'Oberpfälzer Verdienstkreuz', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Regionale bayerische Struktur, 11- und 22-Jahre-Regel', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Verband Ostbayerischer Faschingsgesellschaften', null, 'Ostbayerischer Sonderorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Niederbayern/Oberpfalz; Fokus auf Prinzenpaare', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Landesverband Oberbayerischer Faschingsvereine', null, 'Oberbayerischer Verdienstorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Faschingshochburg München/Umland; Eventfokus', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund der Karnevalisten an Rhein, Mosel und Lahn', null, 'Rhein-Mosel-Lahn-Verdienstmedaille', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Klassische rheinische Staffelung (Eifel/Mosel-Raum)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Ausschuss Aachener Karneval e.V.', null, 'Goldenes Ehrenzeichen', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Lokale Besonderheit im BDK (Stadtebene)', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Festausschuss Bonner Karneval e.V.', null, 'Bonner Stadtsiegel-Orden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Stadtebene Bonn, strenge Vergabe nur für Traditionskorps', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Gemeinschaft Dürener Karneval e.V.', null, 'Dürener Verdienstnadel', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Lokaler Kreisverband im BDK', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Karnevalsverband links und rechts des Rheins', null, 'Rheingold-Orden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Grenzübergreifend NRW/Rheinland-Pfalz', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Kreiskarnevalsverband Heinsberg e.V.', null, 'Heinsberger Verdienstkreuz', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Westlichster Verband Deutschlands', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Münsterländer Karnevalsverband e.V.', null, 'Münsterland-Verdienstmedaille', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Spezifisch für das Münsterland; hohe Hürden für Fremde', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Regionalverband Karnevalistischer Korporationen', null, 'RKK-Verdienstmedaille in Gold', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Großer Verband, teils konkurrierend aber kooperierend', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Südwestdeutscher Karnevalsverband e.V.', null, 'Südwest-Ehrenring', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Historischer Verband im südbadischen Raum', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Verband Hessischer Fastnachtsvereine e.V.', null, 'Hessen-Löwe in Gold', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Zuständig für Süd- und Mittelhessen', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Verband Schleswig-Holsteinischer Karnevalisten', null, 'Nordlicht-Orden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Nördlichster Verband, Fokus auf Minderheiten & Integration', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Bund Karnevalistischer Organisationen Ulm', null, 'Ulmer Spatz in Gold', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Lokaler Verband an der Donau; Donauraum-Sonderstufe', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Vereinigung Trierer Karnevalisten e.V.', null, 'Trierer Kaiserorden', null, null::int, 'Spitzenorden', 'Kriterien nicht hinterlegt. Verbandssystem laut Kompendium: Älteste Kulturstadt Deutschlands, Fokus auf historische Bezüge', 'Im Kompendium als höchster Spitzenorden des Verbandes genannt.'),
  ('Kölner Festkomitee von 1823 e.V.', null, 'Verdienstorden des Kölner Karnevals', null, null::int, 'Verdienstorden', 'Kriterien nicht hinterlegt. Laut Kompendium zählt vor allem der strukturelle Beitrag zum Erhalt des Kölner Ur-Brauchtums und die Arbeit in den Kölner Traditionskorps.', null)
) x(organisation, serie, name, stufe, stufe_nr, kategorie, voraussetzungen, bemerkung)
join public.ehrungs_organisationen o on o.name = x.organisation
where not exists (select 1 from public.ehrungsarten a where a.typ = 'verband' and a.organisation_id = o.id and a.name = x.name);

insert into public.ehrungs_regeln (ehrungsart_id, berechnung, jahre, bemerkung)
select a.id, x.berechnung, x.jahre, x.bemerkung
from (values
  ('Verdienstorden in Silber', 'aktiv', 15::numeric, 'Laut Kompendium: 15 Jahre aktive Arbeit'),
  ('Verdienstorden in Gold', 'aktiv', 25::numeric, 'Laut Kompendium: 25 Jahre aktive Arbeit'),
  ('Verdienstorden in Gold mit Brillanten', 'manuell', null::numeric, 'Laut Kompendium: 40 Jahre ununterbrochen, Einzelfallprüfung')
) x(name, berechnung, jahre, bemerkung)
join public.ehrungsarten a on a.name = x.name and a.typ = 'verband'
join public.ehrungs_organisationen o on o.id = a.organisation_id and o.name = 'Bund Deutscher Karneval e.V.'
where not exists (select 1 from public.ehrungs_regeln r where r.ehrungsart_id = a.id);
